sudo: true
language: nix
script:
- reflex-platform/try-reflex
- nix-build -A ghcjs.frontend
- sudo cp result/ghcjs/frontend/bin/RDWP-exe.jsexe/index.html result/ghcjs/frontend/bin/RDWP-exe.jsexe/404.html
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: result/ghcjs/frontend/bin/RDWP-exe.jsexe
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  repo: aidatorajiro/RDWP-dist
  target-branch: master
  keep-history: true
