sudo: true
language: nix
cache:
  directories:
  - /nix
  timeout: 10000
script:
- nix-build --option extra-binary-caches https://nixcache.reflex-frp.org --trusted-public-keys "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI="
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: result/ghcjs/frontend/bin/RDWP-exe.jsexe
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  repo: aidatorajiro/RDWP-dist
  target-branch: master
  keep-history: true