services:
  - docker
script:
- docker build -f build-tools/docker-nix/Dockerfile -t myimage .
- docker run -itd --name mycontainer myimage
- mkdir RDWP-exe.jsexe
- chmod 777 RDWP-exe.jsexe
- sudo docker cp mycontainer:/home/nix/RDWP/result/bin/RDWP-exe.jsexe ./
- sudo cp RDWP-exe.jsexe/index.html RDWP-exe.jsexe/404.html
- sudo cp frontend/assets/* RDWP-exe.jsexe
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: RDWP-exe.jsexe/
  github-token:
    secure: "mCF+b0iUw0PQnZ08Xu7Lu+6Dyfhs2ZVanpzxoV1Rx5KXKPgdOSFmdqMct59yUSLKp8pG0ITj6FMmsj7OnT9stbBQBTOQsC6YWqJQTr+o3S8h3exfm9XhNnmOu5BQ8n/0Xvs3HItgmsGbUcKVeysyGBPTNh6pH+/ao9YdqjCxbCByzsD2LTYcNaCbkZqpI+wzVd8H6prO3cmGWJrzdPhP/64achYj6WiEOzb6lYgYdIoO9WxuFCC7Vzi6oj68WM6DrcA+0jaW1eqYa16QRNJUJDTXhe2YQYAUpgNtcWbtBmwgqkzVz/oVSN9bnDl+iKr0on4Ml6IBQ/9sdbStQIh8ik9DUzyizkOeX4Z8/PDUHnbfw7v3Stl3roExpfUJv8K9WUSnLNPDtnRSjOlYalOmkBZ4qQ4lf/8ttlvD3FRRNBNs3hLADsuAnxe+JYCu+JUx/JdDB8K7Qk+7NrSWXkPVbmJVdMiFD0Yew59OvEDsGmHrQyv6ENnWULGwKwiJRxGynhuC1fvFSkz2z/OUydH6MJJrB+LaP0gItDohyhOq5hyN74y69fPHRm97mcF8inUwnXMGXDkj28LDYo44/6ruEpbK/HDHOf7nUmhMcqrmlpJpEuvnFHgm7dlfYPPVtUXQtsxhpmSa5yHQ5B1vFeSuRy38lfINYc6653nzKqWqKYk="
  on:
    branch: master
  repo: aidatorajiro/RDWP-dist
  target-branch: master
  keep-history: false
