version: '2'
services:
  myservice:
    build: .
    mem_limit: 11g
    ports: ["127.0.0.1:2222:22", "0.0.0.0:11923:11923"]
    volumes:
      - .:/workspace:cached
      - .stack-cache:/home/haskell/.stack
    command: /bin/sh -c "sudo /etc/init.d/ssh start; cd /workspace; . ~/e.sh; yarn; node ./browsersync.js"
