version: '2'
services:
  myservice:
    image: taw3/ghcjs-devenv:latest
    mem_limit: 11g
    ports: ["127.0.0.1:2222:22"]
    volumes:
      - .:/workspace:cached
      - .stack-cache:/home/haskell/.stack
      - .cabal-cache:/home/haskell/.cabal
    command: /bin/sh -c "sudo /etc/init.d/ssh start; while sleep 1000; do :; done"
