version: '2'
services:
  myservice:
    build: .
    mem_limit: 11g
    ports: ["127.0.0.1:2222:22"]
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "sudo /etc/init.d/ssh start; while sleep 1000; do :; done"
