name:                RDWP
version:             0.1.0.0
github:              "aidatorajiro/RDWP"
license:             MIT
author:              "Torajiro Aida"
maintainer:          "kawarusosu@zoho.com"
copyright:           "2018 Torajiro Aida"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/aidatorajiro/RDWP#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- file-embed
- ghcjs-base
- mtl
- parsec
- random
- reflex
- reflex-dom
- text
- time

library:
  source-dirs: src

executables:
  RDWP-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RDWP
