resolver: lts-8.11
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b

packages:
- '.'
- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: 687b41474f1cacf26b93e981340c7e5c8fccc01d
- location:
    git: https://github.com/reflex-frp/reflex-dom.git
    commit: 9a0a7d9dada8dcc452dc3b3a611a7d022ebd89b6
  subdirs:
  - reflex-dom-core
  - reflex-dom

extra-deps:
- dependent-sum-template-0.0.0.6
- ghcjs-dom-0.9.2.0
- ghcjs-dom-jsffi-0.9.2.0
- jsaddle-0.9.4.0
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1

flags: {}

extra-package-dbs: []